from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator
import random
import csv
from pathlib import Path

shots = 20
simulator = AerSimulator()

qc = QuantumCircuit(1, 1)
qc.h(0)
qc.measure(0, 0)

compiled = transpile(qc, simulator)

quantum_bits = []

for _ in range(shots):
    result = simulator.run(compiled, shots=1).result()
    counts = result.get_counts()
    bit = list(counts.keys())[0]
    quantum_bits.append(int(bit))

classical_bits = [random.randint(0, 1) for _ in range(shots)]

print("Day 07 Classical vs Quantum Randomness")
print("Classical Random Numbers:")
print(classical_bits)
print("Quantum Random Numbers:")
print(quantum_bits)

Path("results/csv").mkdir(parents=True, exist_ok=True)

output_file = "results/csv/day07_classical_vs_quantum_randomness.csv"

with open(output_file, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["day", "project", "index", "classical_bit", "quantum_bit"])

    for index, (classical, quantum) in enumerate(zip(classical_bits, quantum_bits), start=1):
        writer.writerow(["Day 07", "Quantum Randomness Laboratory", index, classical, quantum])

print("Saved comparison to:", output_file)

print("\nComparison Summary:")
print("Classical randomness is generated using a software algorithm.")
print("Quantum randomness is generated by preparing a qubit in superposition and measuring it.")
